name: auto-merge-valid-member-prs
on:
  schedule:
    - cron: '0 0,12 * * *'  # Runs at 00:00 and 12:00 UTC every day
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge-valid-member-prs:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Run Scheduled PR Reviews
        run: node .github/workflows/pr-review.js 
